import {
  User,
  Heart,
  Activity,
  Baby,
  Brain,
  Bone,
  Eye,
  MessageCircle,
  Dna,
  Coffee,
  Smile,
} from "lucide-react";
import type { Doctor } from "../types/doctorTypes";
import { DoctorAvatar2, DoctorAvatar3 } from "@/core/images";

export const categories = [
  { id: "all", name: "Tüm Doktorlar", icon: <User /> },
  { id: "cardiologist", name: "Kardiyolog", icon: <Heart /> },
  { id: "dermatologist", name: "Dermatolog", icon: <Activity /> },
  { id: "pediatrician", name: "Pediatrist", icon: <Baby /> },
  { id: "neurologist", name: "Nörolog", icon: <Brain /> },
  { id: "orthopedic_surgeon", name: "Ortopedik Cerrah", icon: <Bone /> },
  { id: "ophthalmologist", name: "Göz Doktoru", icon: <Eye /> },
  { id: "psychiatrist", name: "Psikiyatrist", icon: <MessageCircle /> },
  { id: "endocrinologist", name: "Endokrinolog", icon: <Dna /> },
  { id: "gastroenterologist", name: "Gastroenterolog", icon: <Coffee /> },
  { id: "dentist", name: "Diş Doktoru", icon: <Smile /> },
];

export const doctors: Doctor[] = [
  {
    _id: "64f7b2a8e9f1c123456789ab",
    name: "Dr. Ahmet Yılmaz",
    email: "ahmet.yilmaz@example.com",
    phone: "+90 532 123 45 67",
    role: "doctor",
    speciality: "Kardiyolog",
    specialityKey: "cardiologist",
    experience: "12",
    fee: "500 TL",
    patients: "1200",
    available: true,
    averageRating: 4.7,
    totalRating: 356,
    about:
      "12 yıllık deneyime sahip, kalp ve damar hastalıkları üzerine uzmanlaşmış bir kardiyolog.",
    appointmentDurationMinutes: 30,
    address: {
      street: "Atatürk Caddesi No:45",
      city: "İstanbul",
      district: "Beşiktaş",
      postalCode: "34353",
      country: "Türkiye",
    },
    appointments: ["apt_001", "apt_002", "apt_003"],
    reviews: [],
    awards: [],
    education: [],
    services: [],
    workingHours: [],
    images: [
      {
        public_id: "doctor_ahmet_yilmaz_1",
        url: DoctorAvatar2,
      },
    ],
    createdAt: "2025-01-10T10:15:30.000Z",
    updatedAt: "2025-10-15T14:22:10.000Z",
  },
  {
    _id: "64f7b2a8e9f1c123456789ab",
    name: "Dr. Ahmet Yılmaz",
    email: "ahmet.yilmaz@example.com",
    phone: "+90 532 123 45 67",
    role: "doctor",
    speciality: "Nörolog",
    specialityKey: "neurologist",
    experience: "12",
    fee: "500 TL",
    patients: "1200",
    available: false,
    averageRating: 4.7,
    totalRating: 356,
    about:
      "12 yıllık deneyime sahip, kalp ve damar hastalıkları üzerine uzmanlaşmış bir kardiyolog.",
    appointmentDurationMinutes: 30,
    address: {
      street: "Atatürk Caddesi No:45",
      city: "İstanbul",
      district: "Beşiktaş",
      postalCode: "34353",
      country: "Türkiye",
    },
    appointments: ["apt_001", "apt_002", "apt_003"],
    reviews: [],
    awards: [],
    education: [],
    services: [],
    workingHours: [],
    images: [
      {
        public_id: "doctor_ahmet_yilmaz_1",
        url: DoctorAvatar3,
      },
    ],
    createdAt: "2025-01-10T10:15:30.000Z",
    updatedAt: "2025-10-15T14:22:10.000Z",
  },
];
